import { configApp } from '@adonisjs/eslint-config'
import { react } from '@adonisjs/eslint-config/react'

export default configApp(...react, {
  // Regenerated by `node ace migration:run`
  ignores: ['database/schema.ts'],
})
